### ISSUE TITLE
Updating a note in Obsidian causes the original note to be deleted and a new note to be created

### ISSUE THREAD

**Issue by chenlijun99** [AwesomeDog/obsidian-awesome-flashcard#1]
Hi, thanks for this cool plugin. I'm planning to develop something similar, so I am gathering ideas from existing Anki plugins.
For me, your plugin's peculiarity is "Minimal footprint", i.e., unlike other plugins, this plugin doesn't store private data on the notes (such as e.g. a note id).
But I think this design goal causes the kind of behavior that I wrote in the title of this issue, which sometimes may be quite bothering. E.g. this would cause the learning progress to be lost for a note in which I want to correct a typo.

Is what I've written correct? Or did I misunderstand how this plugin works and actually there is not this kind of problem?

**Comment by AwesomeDog** [comment]
> Hi, thanks for this cool plugin. I'm planning to develop something similar, so I am gathering ideas from existing Anki plugins. For me, your plugin's peculiarity is "Minimal footprint", i.e., unlike other plugins, this plugin doesn't store private data on the notes (such as e.g. a note id). But I think this design goal causes the kind of behavior that I wrote in the title of this issue, which sometimes may be quite bothering. E.g. this would cause the learning progress to be lost for a note in which I want to correct a typo.
> 
> Is what I've written correct? Or did I misunderstand how this plugin works and actually there is not this kind of problem?

Yeah, you got it right. Updating a note will certainly cause a loss of study process. 

The reason behind it is a balance between re-studying updated cards and storing private data.

The cost of re-studying card is not that scary. Updating a note is not a common practice: about 1 in 20 or less from my experience. And the lost study process will be caught up fairly quickly, due to Anki's algorithm. Since you are grading your new card's familiarity yourself: the lost study process only cause a re-grading once. Apart from that, a new Anki card is quite similar to a learned card.

And storing private data is not so tantalizing to me. Because it causes bond to a specific tool like Anki or a plugin. And an extra mark on note might bother writing or thinking activities, more or less.

**Comment by chenlijun99** [comment]
Thanks for the confirmation!

> The cost of re-studying card is not that scary. Updating a note is not a common practice

I guess it depends on the personal approach in Anki note creation. Some people prefer to create unpolished notes first and then gradually polish them and even add additional insights and remarks, not to mention the correction of avoidable typos.
Although, it may also be argued that after a note has been significantly updated, it makes sense that it must be re-learned from scratch.

> And storing private data is not so tantalizing to me. Because it causes bond to a specific tool like Anki or a plugin. And an extra mark on note might bother writing or thinking activities, more or less.

100% agree, that's why I was looking for a way to keep the association between the note in the markdown file and the note in Anki without leaving the "id" footprint in the markdown source, but couldn't come up with anything except some non-robust heuristic based on edit-distance.

I guess in my tool I'll try to support both approaches.

Thanks for the reply. I'll close this issue since you confirmed that it is an intentional design choice.
